name: paged_datatable
description: A brand new way of creating paginated DataTables in Flutter with sorting and filters
version: 2.0.0-dev.1
homepage: https://github.com/tomasweigenast/paged-datatable

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  intl_utils: ^2.8.5
# flutter:
#   generate: true

# flutter_intl:
#   enabled: true
#   class_name: PagedDataTableLocalization
#   main_locale: en
#   arb_dir: lib/l10n
#   output_dir: lib/l10n/generated
#   use_deferred_loading: false
