name: paged_datatable
description: A brand new way of creating paginated DataTables in Flutter with sorting and filters
version: 2.2.0-dev1.1
homepage: https://github.com/tomasweigenast/paged-datatable
screenshots:
  - description: "This screenshot shows the PagedDataTable with a list of rows."
    path: resources/screenshot1.png
  - description: "This screenshot shows the Filter by popup."
    path: resources/screenshot2.png
  - description: "This screenshot shows a bunch of filters that are applied to the datatable."
    path: resources/screenshot3.png
  - description: "This screenshot shows the PagedDataTable with per-row colors and the Sort by icon."
    path: resources/screenshot4.png
  - description: "This screenshot shows a LargeTextField column, which displays a popup to edit the cell's content."
    path: resources/screenshot5.png

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.5

flutter:
  generate: true

flutter_intl:
  enabled: true
  class_name: PagedDataTableLocalization
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
  use_deferred_loading: false
