name: paged_datatable
description: A brand new way of creating paginated DataTables in Flutter with sorting and filters
version: 1.0.7
homepage: https://github.com/tomasweigenast/paged-datatable

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.3
  intl: ^0.17.0
  stream_transform: ^2.0.0
  equatable: ^2.0.3
  collection: ^1.16.0
  calendar_date_picker2: ^0.3.5
  flutter_hooks: ^0.18.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  intl_utils: ^2.8.1

flutter:
  generate: true

flutter_intl:
  enabled: true
  class_name: PagedDataTableLocalization 
  main_locale: en 
  arb_dir: lib/l10n 
  output_dir: lib/l10n/generated
  use_deferred_loading: false